run:
  timeout: 3m

linters:
  enable:
    - revive
    - ineffassign
    - misspell
    - goimports
    - ginkgolinter
  disable:
    - structcheck # Enable again when there is support for go1.18, see https://github.com/golangci/golangci-lint/issues/2649

severity:
  default-severity: error

linters-settings:
  revive:
    severity: error
    rules:
      - name: if-return
        disabled: true
