run:
  timeout: 3m

linters:
  enable:
    - revive
    - ineffassign
    - misspell
    - goimports
    - ginkgolinter

severity:
  default-severity: error

linters-settings:
  revive:
    severity: error
    rules:
      - name: if-return
        disabled: true
